export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_POSTS_FAIL = 'LOAD_FAIL';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';

export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const LOAD_COMMENTS_FAIL = 'LOAD_COMMENTS_FAIL'

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SIGN_OUT = 'SIGN_OUT';