import React from 'react'

import Aux from '../../hoc/Aux/Aux'
import styles from './About.module.css';

const aboutMe = (props) => {
    return (
        <Aux>
            <div className={styles.section}>
                <p className={styles.title}>Yongkyun Daniel Lee</p>
            </div>
            <div className={styles.section}>
                <div className={styles.sectionTitle}>Dreams/Life Goals</div>
                <div className={styles.subSection}>
                    <p>Develop technology or service that makes people happy.</p>
                    <p>Design and build an amusement park or a roller coaster.</p>
                    <p>Enhance the educational system of Korea.</p>
                </div>
            </div>
            <div className={styles.section}>
                <div className={styles.sectionTitle}>Experience</div>
                <div className={styles.subSection}>
                    <p className={styles.subSectionTitle}>EditCollective - Software Engineer Intern</p>
                    <div className={styles.subSectionDate}><i>Jun 2016 - Sep 2016</i></div>
                    <div className={styles.subSectionContent}>
                        <p>Wrote Python code in Rhinoceros 3D/Grasshopper for computational 
                        design/architecture.</p>
                        <p>Built finger joint structures connecting pieces of forms used to 
                        manufacture concrete pieces for Seoul National University pavilion project.</p>
                        <p>Built components for the view analysis project.</p>
                    </div>
                </div>
                <div className={styles.subSection}>
                    <p className={styles.subSectionTitle}>Gwangju Institute of Technology - Research Intern</p>
                    <div className={styles.subSectionDate}><i>Jun 2014 - Jul 2014</i></div>
                    <div className={styles.subSectionContent}>
                        <p>Investigated the chirping sound generated by collision of two steel 
                        balls through theory and experiments.</p>
                        <p>Presented the research on the 21st International Congress on Sound 
                        and Vibration (ICSV21), Beijing, China.</p>
                    </div>
                </div>
            </div>
            <div className={styles.section}>
                <div className={styles.sectionTitle}>Projects</div>
                <div className={styles.subSection}>
                    <p className={styles.subSectionTitle}>Modular Activated Landing Gear for Unmanned 
                    Aerial Vehicles</p>
                    <div className={styles.subSectionDate}><i>Jan 2016 - Jun 2016</i></div>
                    <div className={styles.subSectionContent}>
                        <p>Built a modular activated landing gear for an unmanned aerial vehicle 
                        to autonomously land on uneven surfaces with inclines up to 15 degrees in 
                        a team of 6.</p>
                        <p>Wrote landing algorithm on Arduino, co-worked on building the landing 
                        platform, and assisted machining the legs of the landing gear. 
                        Presented at Drones Data X 2016 in San Francisco.</p>
                    </div>
                </div>
                <div className={styles.subSection}>
                    <p className={styles.subSectionTitle}>Self-stabilizing Conveyor System</p>
                    <div className={styles.subSectionDate}>Dec 2015</div>
                    <div className={styles.subSectionContent}>
                        <p>Built self-stabilizing conveyor system using Arduino in a 5 member team. 
                        Co-worked on programming the source code with one other student.</p>
                        <p>The first US team to win in competition history.</p>
                        <p>You can find the whole story <a className={styles.link} href="https://www.thalesgroup.com/en/united-states/news/thalesarduino-and-winner">here</a>.</p>
                        <p><a className={styles.link} href="https://github.com/noninertialframe/Self-stabilizing-conveyor-system-Arduino-sourcecode">Github repository</a> 
                        of the source code (details explained in description and code)</p>
                    </div>
                </div>
            </div>
            <div className={styles.section}>
                <div className={styles.sectionTitle}>Trivia</div>
                <div className={styles.subSection}>
                    <div className={styles.subSectionContent}>
                        <p>I have ridden Formula Rosa, the fastest rollercoaster in the world, in Ferrari World, Abu Dhabi.</p>
                        <p>I have worked as a Crew Leader in <i>Habitat for Humanity</i>.</p>
                        <p>I am a big fan of the TV show "Silicon Valley" and the movie "Social Network."</p>
                    </div>
                </div>
            </div>
            <div className={styles.section}>
                <div className={styles.sectionTitle}>Contact</div>
                <div className={styles.subSection}>
                    <div className={styles.subSectionContent}>
                        <p>Email - ylee2@caltech.edu</p>
                        <p>Linkedin - <a className={styles.link} href="https://www.linkedin.com/in/yongkyunlee/">Link</a></p>
                    </div>
                </div>
            </div>
        </Aux>
    );
}

export default aboutMe;